server:
  port: 8082
spring:
  profiles:
    active: qa
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/springpractice
    password: Stashy4224!!!
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
logging:
  level:
    org:
      springframework:
        security: DEBUG
welcome:
  message: Welcome to SPRINGBOOT!

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/springpractice-prod
    password: Stashy4224!!!
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
logging:
  level:
    org:
      springframework:
        security: DEBUG
welcome:
  message: Welcome to SPRINGBOOT!

---
spring:
  config:
    activate:
      on-profile: qa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/springpractice-qa
    password: Stashy4224!!!
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
logging:
  level:
    org:
      springframework:
        security: DEBUG
welcome:
  message: Welcome to SPRINGBOOT!

management:
  endpoint:
    configprops:
      show-values: ALWAYS
    env:
      show-values: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans